name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.keshav25101990 }}
        password: ${{ secrets.India#123 }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.keshav25101990 }}/demoapp:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.keshav25101990 }}/demoapp:latest